spring:
  datasource:
    url: jdbc:h2:file:./.data/petregdb
    driver-class-name: org.h2.Driver
    username: sa
    password:

mybatis:
  configuration:
    map-underscore-to-camel-case: true

logging:
  level:
    org.springframework.web: debug
    org.springframework.http: trace
